const { Model, DataTypes } = require('sequelize');
const sequelize = require('../config/connection');

class List extends Model { }

List.init(
    {
        // A UUID column to uniquely identify each to-do list. 
        // It has a default value generated by UUIDV4 function and is set as the primary key.
        id: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true,
            allowNull: false
          },
        // A string column to store the title of the to-do list.
          title: {
            type: DataTypes.STRING,
            allowNull: false
          },
        // A text column to store the description of the to-do list.
          description: {
            type: DataTypes.TEXT,
            allowNull: false
          },
        // A date column to store the creation date of the to-do list.
        // It has a default value of the current date and time generated by NOW function.
          createdAt: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: DataTypes.NOW
          },
        // A date column to store the due date of the to-do list.
          dueDate: {
            type: DataTypes.DATE,
            allowNull: false
          },
        // An integer column to store the user ID of the user who created the to-do list.
        // It has a foreign key constraint to the user table. References the id columns of the user model.
          userId: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
              model: 'user',
              key: 'id'
            }
    },
    },
    {
        sequelize,
        timestamps: false,
        freezeTableName: true,
        underscored: true,
        modelName: 'list'
    }
);

module.exports = List